from enum import Enum

class RepeatType(Enum):
    DAILY = "DAILY"
    SPECIFIC_WEEKDAYS = "SPECIFIC_WEEKDAYS"
    SPECIFIC_MONTH_DAYS = "SPECIFIC_MONTH_DAYS"
    N_TIMES_PER_WEEK = "N_TIMES_PER_WEEK"
    N_TIMES_PER_MONTH = "N_TIMES_PER_MONTH"
    EVERY_N_DAYS = "EVERY_N_DAYS"